In [1]:
# Importing Modules 
import cv2
import numpy as np 

In [2]:
# reading Image 
img=cv2.imread('gg.jpg')  # '0' will give  grayscale image and '1' will give colored image 
#print(img)             # numpy array - as image is converted into numpay arrays 
print(img.shape)
print(type(img))

(398, 480, 3)
<class 'numpy.ndarray'>


In [3]:
#showing image 
cv2.imshow('face',img)
cv2.waitKey(10)         # image will be shown for 0 miliseconds 
cv2.destroyAllWindows() # closes all windows 

In [4]:
cv2.imshow('img',img)
cv2.waitKey(2000)      # image will be shown for 20000 miliseconds 
cv2.destroyAllWindows()

In [5]:
# Resize the image 
resized_image=cv2.resize(img,(int(img.shape[1]*2),int(img.shape[0]*2)))   #double the image size 
cv2.imshow('resize',resized_image)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [6]:
# Datecting Face using cascade classifier(contains predefined face features)
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')   #creating a cascade classifier 


# reading the image 
img=cv2.imread('gg.jpg')


#Reading the image as a grayscale image 
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)      #converting image into grayscale image 


#Search the coordinates of the image 
faces=face_cascade.detectMultiScale(gray_img,scaleFactor=1.05,minNeighbors=5)      
#'detectMultiScale' is the method to search the face rectangle coordinates 
#'scalefactor' decreases the shape value by 5% ,until the face is found ,
#Smaller the scaleFactor greater the accuracy 


#Drawing a rectange 
for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
    # rectange is the method to draw rectange 
    #x,y,x+w,y+h are the coordinates of the rectange 
    #(0,255,0) is the BGR value of the ractange   ---- Range=(0 to 255)   
    # 3 is the width of the rectangle 
    

cv2.imshow('face',img)
cv2.waitKey(2000)
cv2.destroyAllWindows()
    

In [7]:
# Capturing video from the camera 
video=cv2.VideoCapture(0)  # Method to create videocapture object.It will trigger the camera 
                           #Either give path to the video file or use numbers.Numbers specify that
                           # you will be using webcam to capture video. '0' means the webcam ,'1' 
                           #  means camera(external) other than webcam connectd to your PC.

            
video.release()         # This will release the camera in some miliseconds.

# Running just this code will switch on the camera light for a second. 
# so here we have to add a time delay


In [8]:
import time              # time Module 
video=cv2.VideoCapture(0)

time.sleep(3)          # This will stop the script for 3 seconds 

video.release()

In [9]:
# Adding windows that shows  the video 

video=cv2.VideoCapture(0)

check,frame =video.read()        #'check' is bool data type, returns true if the python is able 
                                  # capture the videoCapture object 
                                 #'frame' is the numpy array, it represents the first image that 
                                  # video captures.
        
print(check)
print(frame)
        
time.sleep(3)

cv2.imshow('video',frame)      # it will display the first frame of the videocapture object 
cv2.waitKey(2000)

video.release()

cv2.destroyAllWindows()

True
[[[165 166 170]
  [162 163 167]
  [172 168 169]
  ...
  [141 133 117]
  [121 129 118]
  [124 132 121]]

 [[157 165 168]
  [157 165 168]
  [161 165 166]
  ...
  [137 129 113]
  [121 127 116]
  [126 132 121]]

 [[154 165 165]
  [156 167 167]
  [158 167 167]
  ...
  [132 128 113]
  [122 126 113]
  [126 130 117]]

 ...

 [[181 183 177]
  [185 187 181]
  [186 189 180]
  ...
  [ 46  61  81]
  [ 45  60  80]
  [ 45  60  80]]

 [[179 183 177]
  [183 187 181]
  [177 187 182]
  ...
  [ 49  63  81]
  [ 49  62  82]
  [ 47  60  80]]

 [[172 183 176]
  [173 184 177]
  [169 184 178]
  ...
  [ 51  64  79]
  [ 49  60  80]
  [ 44  55  75]]]


In [10]:
# In order to capture the video we will be using the while loop. While condition is such that,
# until 'check' is true,Python will display the frames.

video=cv2.VideoCapture(0)

a=1

while True:
    a=a+1
    check,frame=video.read()
    
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    cv2.imshow('capturing',gray)
    
    key=cv2.waitKey(1)         # This will generate a new frame after every miliseconds 
    
    if key==ord('q'):          # when you press q the window will get destroyed 
        break
    
    
print(a)           # print the number of frames 
video.release()
cv2.destroyAllWindows()

281


In [11]:
# Detecting face in video 

face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

video=cv2.VideoCapture(0)

while True:
    check,frame=video.read()
    
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    faces=face_cascade.detectMultiScale(gray,scaleFactor=1.05,minNeighbors=5)
    
    for x,y,w,h in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(20,25,200),2)
        
    
    cv2.imshow('capturing',frame)
    
    key=cv2.waitKey(1)
    
    if key==ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()

## Face Recognition 


In [45]:
#Face Recognizer 

import cv2
import os          # os module for reading training data directories and paths 
import numpy as np 


In [46]:
# As OpenCV face recognizer accepts labels as integers so we need to define a mapping between 
# integer labels and persons actual names so below I am defining a mapping of persons integer
# labels and their respective names.

#there is no label 0 in our training data so subject name for index/label 0 is empty
subjects=['','Aalia_Bhatt','Aamir_khan','Ranvir_singh','Sharukh_Khan','Taapsee_Pannu']


In [47]:
#Preparing the data 

# Function to detect face using opencv 
def detect_face(img):
    
    gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)   #Converting to grayscale
    
    face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    
    faces=face_cascade.detectMultiScale(gray,scaleFactor=1.05,minNeighbors=5)
    
    #if no face is detected then return original image 
    if(len(faces)==0):
        return None,None
    
    # extract face area 
    (x ,y,w,h)=faces[0]
    
    #return only face part 
    return gray[y:y+w,x:x+h], faces[0]


    

In [48]:
#this function will read all persons' training images, detect face from each image
#and will return two lists of exactly same size, one list 
# of faces and another list of labels for each face

def prepare_training_data(data_folder_path):
    
    # get the directories(one directory for each subject) in data folder 
    dirs=os.listdir(data_folder_path)
    
    #list to hold all subject faces 
    faces=[]
    
    # list to hold labels for all subject faces 
    labels=[]
    
    for dir_name in dirs:
        
        #our subject directories start with letter 's' so
        #ignore any non-relevant directories if any
        if not dir_name.startswith('s'):
            continue
        
        
         #extract label number of subject from dir_name
        #format of dir name = slabel
        #, so removing letter 's' from dir_name will give us label
        label=int(dir_name.replace('s',''))
        
        #built path of directory containing images for current subject 
        # sample subject_dir_path='training-data/s1'
        subject_dir_path=data_folder_path+'/'+dir_name 
        
        #get the images names  that are inside the subject directory 
        subject_images_names= os.listdir(subject_dir_path)
        
        # go through each image name ,read image ,detect face ,and add face to the list of faces 
        for image_name in subject_images_names:
            
            #build image path 
            #same image path=training-data/s1/1.pgm
            image_path=subject_dir_path+'/'+image_name 
            
            #read image 
            image=cv2.imread(image_path)
            
            #display an image window to show the image 
            cv2.imshow('training on image ....',image)
            cv2.waitKey(100)
            
            #detect face using function detect_face 
            face,rect=detect_face(image)
            
            if face is not None:
                #add face to faces list 
                faces.append(face)
                #add label for this face 
                labels.append(label)
                
    cv2.destroyAllWindows()
    cv2.waitKey(1)
    cv2.destroyAllWindows()
    return faces,labels 


In [49]:
# prepare the trainingg data 
# data will be in two list of same size 
# one will contain faces and other will contain labels for each face 

faces,labels=prepare_training_data('training_data')

print('total faces',len(faces))
print('total labels',len(labels))

total faces 49
total labels 49


In [50]:
#traning face recognizor 

#OpenCV has three face recognizor ,we can use any one of them 
#1-EigenFace Recognizer
#2-FisherFace Recognizer
#3-LocalBinaryPatternsHistogram(LBPH) Recognizer 

# create the LBPH face recognizor 
face_recognizer=cv2.face.LBPHFaceRecognizer_create()

#train face recognizor 
face_recognizer.train(faces,np.array(labels))


In [59]:
#function to draw rectangle on image 
def draw_rectangle(img,rect):
    (x,y,w,h)=rect
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    
    
#function to draw text on image 
def draw_text(img,text,x,y):
    cv2.putText(img,text,(x,y),cv2.FONT_HERSHEY_PLAIN,1.5,(0,255,0),2)
    

In [87]:
# function that recognizes the test image 
def predict(test_image):
    img=test_image.copy()
    
    #detect face from the image 
    face,rect=detect_face(img)
    
    #predict the face using our face recognizer 
    label=face_recognizer.predict(face)
    
    # get name of the respective label returned by face recognizer 
    label_text=subjects[label[0]]
    
    
    #draw a rectangle around the face detected 
    draw_rectangle(img,rect)
    
    # draw name of the predicted image 
    draw_text(img,label_text,rect[0],rect[1]-5)
    
    return img


In [89]:
#predicting image 
print('predicting image ....')

#load test images 
test_img1=cv2.imread('test_data/test3.jpg')
test_img2=cv2.imread('test_data/test4.jpg')

# perform a prediction 
predicted_img1=predict(test_img1)
predicted_img2=predict(test_img2)

print('prediction complete')

#display both images 
cv2.imshow('test1',predicted_img1)
cv2.imshow('test2',predicted_img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

predicting image ....
prediction complete
